#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [3]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.DataFrame'>

In [7]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

In [ ]:
''' 
| Series        | DataFrame            |
| ------------- | -------------------- |
| 1-D           | 2-D                  |
| Single column | Multiple columns     |
| Has index     | Has rows and columns |
| `pd.Series()` | `pd.DataFrame()`     |

Series = 1D labeled array (like a single Excel column).
Default index = 0,1,2,...
Dictionary keys become the index of a Series.
Custom index can be given using index=[...].
DataFrame = Collection of Series arranged as rows and columns (like an Excel sheet).
pd.Series() → creates a Series.
pd.DataFrame() → creates a DataFrame

'''

In [9]:
df=pd.read_csv('data.csv')
df.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [10]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [12]:
### Accessing Data From Dataframe
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [14]:
df['Name'] ##Notice this is one column, so Pandas returns a Series.
print(df['Name'])

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [9]:
df.loc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [ ]:
df.iloc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [ ]:
'''
Suppose
df.index = [100,200,300]


Now
df.loc[100]
returns
Krish
because 100 is the label.

But

df.iloc[0]
also returns Krish because it's the 0th position.

So
loc → label/index based
iloc → integer position based

This difference becomes important when your index is not 0,1,2,....
'''

In [34]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [ ]:
## Accessing a specified element 
df.at[2,'Age']

np.int64(45)

In [ ]:
''' 
Syntax
df.at[row_label, column_name]

Returns one value.
It is optimized for fast scalar access.

'''

In [12]:
df.at[2,'Name']

'Jack'

In [ ]:
## Accessing a specified element using iat
df.iat[2,2]

''' 
Row 2
Column 2

'''

'Florida'

In [ ]:
'''  

pd.read_csv() → Reads a CSV file into a DataFrame.
head(n) → First n rows (default = 5).
tail(n) → Last n rows (default = 5).
df["Column"] → Returns a Series (single column).
loc → Label-based indexing (row_label, column_name).
iloc → Integer position-based indexing (row_position, column_position).
at → Fast access to a single value using label + column name.
iat → Fast access to a single value using row position + column position.

| Function    | Uses                 | Based On            | Returns          |
| ----------- | -------------------- | ------------------- | ---------------- |
| `head(n)`   | First n rows         | -                   | DataFrame        |
| `tail(n)`   | Last n rows          | -                   | DataFrame        |
| `df["col"]` | One column           | Column name         | Series           |
| `loc`       | Row/column selection | Label               | Series/DataFrame |
| `iloc`      | Row/column selection | Position            | Series/DataFrame |
| `at`        | Single value         | Label + Column name | Scalar           |
| `iat`       | Single value         | Position + Position | Scalar           |
| `drop()`    | Remove rows/columns  | Label               | New DataFrame    |

'''

In [ ]:
df.drop(0)

'''  
Row 0 is removed in the returned DataFrame.
Very Important
The original DataFrame is not modified


still gives
Krish
John
Jack
because
drop() returns a new DataFrame.

To permanently remove:
df = df.drop(0)
or
df.drop(0, inplace=True)
'''

   Name  Age      City
1  John   30  New York
2  Jack   45   Florida

In [18]:
### Data MAnipulation with Dataframe
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [ ]:
## Adding a column
df['Salary']=[50000,60000,70000] #The number of values must match the number of rows
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   45    Florida   70000

In [ ]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

''' 
Why axis=1?
Pandas has two axes.
axis=0 → Rows
axis=1 → Columns

'''

In [22]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [48]:
## Add age to the column
df['Age']=df['Age']+1
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   46    Florida

In [ ]:
df.drop(0,inplace=True)

'''  
Notice

Index is still
1
2

It does not become
0
1

To reset the index:
df.reset_index(drop=True, inplace=True)

'''

In [52]:
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida

In [53]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [54]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.describe()
''' 
df.describe()
Returns statistical summary of numeric columns.


'''

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
##🎯 Interview Tip
'''
A common interview question is:
Q: Why is the Date column shown as object after read_csv()?
Answer: Because read_csv() reads dates as strings by default. Convert them using:
df["Date"] = pd.to_datetime(df["Date"])
This is a frequently tested concept in Data Analyst interviews.
'''

''' 
df["NewCol"] = values → Add a new column (values count must equal rows).
df.drop("Col", axis=1) → Drop a column (axis=1 = columns).
df.drop(row_label, axis=0) → Drop a row (axis=0 = rows, default).
inplace=True → Modify the original DataFrame.
df["Age"] = df["Age"] + 1 → Vectorized column operation (fast, no explicit loop).
df.reset_index(drop=True) → Reset row indices after deleting rows.
df.dtypes → Displays the datatype of each column.
df.describe() → Statistical summary of numeric columns:
count → Non-null values
mean → Average
std → Standard deviation
min → Minimum
25% → First quartile (Q1)
50% → Median
75% → Third quartile (Q3)
max → Maximum


'''